### ISSUE TITLE
Is it hard to make this work for version for 0.100.0?

### ISSUE THREAD

**Issue by oderwat** [ainvaltin/nu-plugin#1]
I tried to create a nu-plugin but it does not work for the current nu-shell version. Is it hard to update the package?

**Comment by ainvaltin** [comment]
Haven't had time to keep up with nu releases... The protocol had some breaking changes lately which are not completely trivial to fix. Hopefully can have a look at it during the weekend.

**Comment by ainvaltin** [comment]
Pushed some fixes, the demo plugin seems to mostly work... the plugin protocol changes haven't been properly documented so it's a bit of guesswork.

**Comment by oderwat** [comment]
I am going to check with my plugin idea. Thank you very much for taking the time!

**Comment by oderwat** [comment]
I am a bit late, but I can now confirm that it works for me! Thank you!

**Comment by oderwat** [comment]
Maybe you want to try the plugin I hacked together quickly: https://github.com/oderwat/nu_plugin_logfmt

**Comment by ainvaltin** [comment]
I have been thinking writing something to work with slog output myself :)
Will definitely try it out next time I have to analyse log locally.
